"""Shared data models for live market intelligence outputs."""

from __future__ import annotations

from dataclasses import dataclass, field, asdict
from datetime import UTC, datetime
from enum import StrEnum
from typing import Any

import pandas as pd


class MarketRegime(StrEnum):
    """Supported live market regime labels."""

    BULLISH_TRENDING = "bullish_trending"
    BEARISH_TRENDING = "bearish_trending"
    SIDEWAYS_CHOPPY = "sideways_choppy"
    VOLATILE_EXPANSION = "volatile_expansion"
    FAKE_BREAKOUT_ENVIRONMENT = "fake_breakout_environment"
    UNKNOWN = "unknown"


class SignalAction(StrEnum):
    """Supported directional option signal outputs."""

    BUY_CE = "buy_ce"
    BUY_PE = "buy_pe"
    SELL_CE = "sell_ce"
    SELL_PE = "sell_pe"
    NO_TRADE = "no_trade"


class OptionSide(StrEnum):
    """Call/put leg selectors."""

    CE = "CE"
    PE = "PE"


@dataclass(slots=True)
class MarketSnapshotBundle:
    """Latest aligned live market state across inputs."""

    timestamp: datetime
    spot_price: float | None
    vix_value: float | None
    spot_frame: pd.DataFrame
    vix_frame: pd.DataFrame
    option_chain_frame: pd.DataFrame
    ticks_frame: pd.DataFrame
    candles_1m: pd.DataFrame
    candles_5m: pd.DataFrame


@dataclass(slots=True)
class LiveFeatures:
    """Live feature frame and convenience payload for downstream engines."""

    frame: pd.DataFrame
    timestamp: datetime
    feature_map: dict[str, float] = field(default_factory=dict)


@dataclass(slots=True)
class RegimeResult:
    """Market regime decision with confidence and rationale."""

    regime: MarketRegime
    confidence: float
    reasons: list[str] = field(default_factory=list)


@dataclass(slots=True)
class ProbabilityResult:
    """Directional expansion probability estimates."""

    bullish_probability: float
    bearish_probability: float
    sideways_probability: float
    confidence: float
    horizon_minutes: int
    evidence: list[str] = field(default_factory=list)


@dataclass(slots=True)
class TrapResult:
    """Trap and fake-breakout diagnostics."""

    fake_breakout_probability: float
    buyer_trap_probability: float
    seller_trap_probability: float
    stoploss_hunt_probability: float
    evidence: list[str] = field(default_factory=list)


@dataclass(slots=True)
class StrikeResult:
    """Automatic strike recommendation."""

    option_side: OptionSide
    strike: float | None
    expiry: str | None
    moneyness: str
    rationale: list[str] = field(default_factory=list)


@dataclass(slots=True)
class RiskResult:
    """Sizing and risk-control output."""

    allowed: bool
    quantity: int
    stop_loss: float | None
    target: float | None
    max_daily_loss_hit: bool
    reason: str


@dataclass(slots=True)
class SignalResult:
    """Final filtered signal generated by the intelligence engine."""

    action: SignalAction
    confidence: float
    regime: MarketRegime
    probability: ProbabilityResult
    trap: TrapResult
    entry_reference: float | None
    stop_loss: float | None
    target: float | None
    strike: StrikeResult | None
    quantity: int
    reasoning: list[str] = field(default_factory=list)


@dataclass(slots=True)
class OpenTrade:
    """Live trade state tracked by the monitor."""

    trade_id: str
    signal: SignalResult
    entry_price: float
    quantity: int
    opened_at: datetime
    status: str = "open"
    last_price: float | None = None
    peak_pnl: float = 0.0
    realized_pnl: float = 0.0


@dataclass(slots=True)
class TradeUpdate:
    """Status update emitted by the live trade monitor."""

    open_trades: list[OpenTrade]
    closed_trades: list[OpenTrade]
    total_pnl: float
    alert_messages: list[str] = field(default_factory=list)


@dataclass(slots=True)
class IntelligenceReport:
    """Complete market intelligence output for a single refresh cycle."""

    timestamp: datetime
    snapshot: MarketSnapshotBundle
    features: LiveFeatures
    regime: RegimeResult
    probabilities: ProbabilityResult
    trap: TrapResult
    signal: SignalResult
    strike: StrikeResult
    risk: RiskResult
    trade_update: TradeUpdate

    def as_dict(self) -> dict[str, Any]:
        """Serialize a report to a plain dictionary for dashboard rendering."""
        return {
            "timestamp": self.timestamp.isoformat(),
            "snapshot": {
                "timestamp": self.snapshot.timestamp.isoformat(),
                "spot_price": self.snapshot.spot_price,
                "vix_value": self.snapshot.vix_value,
            },
            "regime": asdict(self.regime),
            "probabilities": asdict(self.probabilities),
            "trap": asdict(self.trap),
            "signal": {
                **asdict(self.signal),
                "action": self.signal.action.value,
                "regime": self.signal.regime.value,
                "strike": None if self.signal.strike is None else asdict(self.signal.strike),
            },
            "strike": asdict(self.strike),
            "risk": asdict(self.risk),
            "trade_update": {
                "open_trades": [asdict(item) for item in self.trade_update.open_trades],
                "closed_trades": [asdict(item) for item in self.trade_update.closed_trades],
                "total_pnl": self.trade_update.total_pnl,
                "alert_messages": list(self.trade_update.alert_messages),
            },
        }


def utcnow() -> datetime:
    """Return a timezone-aware UTC timestamp."""
    return datetime.now(UTC)
